### ISSUE TITLE
Error while Building SDK

### ISSUE THREAD

**Issue by moumenra** [BelledonneCommunications/linphone-windows10#1]
Error	MSB6006	"cmd.exe" exited with code 1. [C:\Users\darthvader\Desktop\deskphone-siarum\linphone-windows10\WORK\win10-x64\Build\linphone\wrappers\csharp\linphonecs.vcxproj] [C:\Users\darthvader\Desktop\deskphone-siarum\linphone-windows10\WORK\win10-x64\cmake\EP_linphone.vcxproj]	SDK_x64	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	171	

Not sure why on the SDK Build

**Comment by DatBewar** [comment]
Hello,
we have worked a lot on the SDK but now it's fixed.
