### ISSUE TITLE
Linphone SDK5.1.0 cannot be found

### ISSUE THREAD

**Issue by simadi** [BelledonneCommunications/linphone-windows10#30]
Linphone SDK5.1.0 cannot be found at the following address
 https://www.linphone.org/releases/windows/sdk, https://www.linphone.org/snapshots/windows/sdk, 

I referenced linphonesdk.5.1.20.nupkg, but it failed to compile

**Comment by soroshsabz** [comment]
ITNOA

I test this project with LinphoneSDK.5.1.56 and build and work successfully

this LinphoneSDK.5.1.56 is available in https://download.linphone.org/releases/windows/sdk/LinphoneSDK.5.1.56.nupkg

**Comment by julonexus** [comment]
Documentation about Nugets can be found from : https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/Windows%20UWP/
